---
- hosts: localhost
  connection: local
  roles:
    - { role: osx, when: ansible_distribution == "MacOSX" }
  vars_prompt:
    - name: "usersethostname"
      prompt: "Set a hostname for this machine?"
      private: no
