---
- hosts: localhost
  connection: local
  roles:
    - { role: osx, when: ansible_distribution == "MacOSX" }
    - git
    - irssi
    - vim
    - zsh
  vars_prompt:
    - name: "usersethostname"
      prompt: "Set a hostname for this machine?"
      private: no
    - name: "upgradebrews"
      prompt: "Ugrade brews?"
      private: no
      when: ansible_distribution == "MacOSX"
