---
- name: copy .gitconfig
  copy: src=.gitconfig dest=~/.gitconfig

- name: copy .gitignore
  copy: src=.gitignore dest=~/.gitignore

- name: copy git hooks
  copy: src=post-merge dest=~/.git/hooks/ mode=0777
