---

- name: tap versions
  homebrew_tap:
    tap: homebrew/versions
    state: present

- name: tap tmate
  homebrew_tap:
    tap: nviennot/tmate
    state: present

- name: update and upgrade brews
  homebrew: update_homebrew=yes upgrade_all=yes
  when: upgradebrews and upgradebrews.length != 0

- name: install brews
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - autojump
    - cowsay
    - docker
    - git
    - gpg
    - gpg2
    - hub
    - irssi
    - mongodb
    - node012
    - openssl
    - pass
    - tmate
    - tmux
    - vim
    - zsh
    - zsh-completions

- name: install cask
  homebrew:
    name: caskroom/cask/brew-cask
    state: present

- name: install casks
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - clipmenu
    - disk-inventory-x
    - flux
    - google-chrome
    - gpgtools
    - heroku-toolbelt
    - xquartz
    - inkscape
    - libreoffice
    - little-snitch
    - mou
    - robomongo
    - slack
    - smartgit
    - sketch
    - skype
    - spotify
    - sublime-text
    - the-unarchiver
    - transmission
    - transmit
    - virtualbox
    - vlc

- name: tap font cask
  homebrew_tap:
    tap: caskroom/fonts
    state: present

- name: install fonts
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - font-source-sans-pro
    - font-source-code-pro
  ignore_errors: yes
