---

- name: tap versions
  homebrew_tap:
    tap: homebrew/versions
    state: present

- name: update and upgrade brews
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install brews
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - autojump
    - cmatrix
    - cowsay
    - curl
    - docker
    - git
    - gnupg21
    - hub
    - irssi
    - mongodb
    - node
    - no-more-secrets
    - openssl
    - pass
    - tmate
    - tmux
    - vim
    - wget
    - zsh
    - zsh-completions

- name: install casks
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - awareness
    - clipmenu
    - disk-inventory-x
    - flux
    - google-chrome
    - gpgtools
    - java
    - xquartz
    - inkscape
    - libreoffice
    - little-snitch
    - mou
    - robomongo
    - slack
    - smartgit
    - sketch
    - skype
    - spotify
    - sublime-text
    - the-unarchiver
    - transmission
    - transmit
    - virtualbox
    - vlc

- name: tap font cask
  homebrew_tap:
    tap: caskroom/fonts
    state: present

- name: install fonts
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - font-source-sans-pro
    - font-source-code-pro
  ignore_errors: yes
