---
- name: Get current Terminal profile
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added
  shell: open roles/osx/files/fijimunkii.terminal
  changed_when: false
  when: "'fijimunkii' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string fijimunkii
    - defaults write com.apple.terminal 'Startup Window Settings' -string fijimunkii
  changed_when: false
  when: "'fijimunkii' not in terminal_theme.stdout"
