---
- name: copy .zshrc
  copy: src=roles/osx/files/.zshrc dest=~/.zshrc

- name: Add zsh to /etc/shells
  lineinfile: dest=/etc/shells regexp="zsh" line="/usr/local/bin/zsh" state=present
  sudo: true

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    update: yes

- name: install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/zsh-syntax-highlighting
    update: yes

- name: set zsh as default shell
  shell: chsh -s /usr/local/bin/zsh
